// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu7qrRngLfkUbtvM_Md9sklIypZYwktZo',
    appId: '1:1067430482171:web:765535cebb1dfeb3ea605e',
    messagingSenderId: '1067430482171',
    projectId: 'ganaderia-c769e',
    authDomain: 'ganaderia-c769e.firebaseapp.com',
    storageBucket: 'ganaderia-c769e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtko7UEqhf8RbNG6v5g_d29d3I6mj2_AE',
    appId: '1:1067430482171:android:779a619600b39f43ea605e',
    messagingSenderId: '1067430482171',
    projectId: 'ganaderia-c769e',
    storageBucket: 'ganaderia-c769e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6-JECDjh-WQPYjKE4mF7_bc08MZX5vhI',
    appId: '1:1067430482171:ios:c529a9fab2611a36ea605e',
    messagingSenderId: '1067430482171',
    projectId: 'ganaderia-c769e',
    storageBucket: 'ganaderia-c769e.appspot.com',
    iosBundleId: 'com.example.ganaderiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6-JECDjh-WQPYjKE4mF7_bc08MZX5vhI',
    appId: '1:1067430482171:ios:c529a9fab2611a36ea605e',
    messagingSenderId: '1067430482171',
    projectId: 'ganaderia-c769e',
    storageBucket: 'ganaderia-c769e.appspot.com',
    iosBundleId: 'com.example.ganaderiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu7qrRngLfkUbtvM_Md9sklIypZYwktZo',
    appId: '1:1067430482171:web:c5bf103cc2d48518ea605e',
    messagingSenderId: '1067430482171',
    projectId: 'ganaderia-c769e',
    authDomain: 'ganaderia-c769e.firebaseapp.com',
    storageBucket: 'ganaderia-c769e.appspot.com',
  );
}
